### PR TITLE
Fix packaging

### LINKED ISSUE #11: Warning in Package Creation
The creation of the snap package is raising some warnings.

```
The 'webots' part is missing libraries that are not included in the snap or base. They can be satisfied by adding the following entries to the existing stage-packages for this part:

- libgeos-3.7.1

This part is missing libraries that cannot be satisfied with any available stage-packages known to snapcraft:

- libglut.so.3

These dependencies can be satisfied via additional parts or content sharing. Consider validating configured filesets if this dependency was built.
```
See: https://travis-ci.com/github/cyberbotics/webots-snap/jobs/296715674#L6759

### PR DESCRIPTION
**Pull request by DavidMansolino**
fix  #11

### CODE REVIEW

**Comment by DavidMansolino** [comment]
The snap issues are gone:
https://travis-ci.com/github/cyberbotics/webots-snap/jobs/360804120#L7296

But there are some issues with the Webots side:

https://travis-ci.com/github/cyberbotics/webots-snap/jobs/360804120#L7285

**Comment by DavidMansolino** [comment]
No more warnings when including these patches too: https://github.com/cyberbotics/webots/pull/1901

https://travis-ci.com/github/cyberbotics/webots-snap/jobs/360851661

**Comment by DavidMansolino** [comment]
No more warnings at all with this branch when using the develop branch of https://github.com/cyberbotics/webots: https://travis-ci.com/github/cyberbotics/webots-snap/jobs/362120803#L7304-L7317

**Review by omichel — APPROVED** [review]
Thank you.

**Pull request merged**
