### PR TITLE
Fix Package Creation

### PR DESCRIPTION
**Pull request by DavidMansolino**
The goal of this PR is to fix the package creation for Webots R2020a

### CODE REVIEW

**Review by omichel — DISMISSED** [review]

**Comment by DavidMansolino** [comment]
I am creating a small wiki page together with this PR: https://github.com/cyberbotics/webots-snap/wiki

**Comment by DavidMansolino** [comment]
I can now generate the snap package using Travis however it's most of time failing because taking more time than the 50min limit.

**Comment by DavidMansolino** [comment]
The package creation finally works on travis: https://github.com/cyberbotics/webots/releases/tag/nightly_20_12_2019

**Comment by DavidMansolino** [comment]
:+1: (:heavy_check_mark: https://github.com/cyberbotics/webots/releases/tag/nightly_3_1_2020)

**Review by omichel — APPROVED** [review]

**Pull request merged**
